[debug] [2020-04-16T22:57:41.153Z] ----------------------------------------------------------------------
[debug] [2020-04-16T22:57:41.155Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Veigas SantoDigital\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js use
[debug] [2020-04-16T22:57:41.155Z] CLI Version:   8.0.3
[debug] [2020-04-16T22:57:41.155Z] Platform:      win32
[debug] [2020-04-16T22:57:41.155Z] Node Version:  v12.16.1
[debug] [2020-04-16T22:57:41.156Z] Time:          Thu Apr 16 2020 19:57:41 GMT-0300 (GMT-03:00)
[debug] [2020-04-16T22:57:41.156Z] ----------------------------------------------------------------------
[debug] [2020-04-16T22:57:41.156Z] 
[debug] [2020-04-16T22:57:41.162Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-16T22:57:41.202Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (C:\Users\Veigas SantoDigital\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (C:\Users\Veigas SantoDigital\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\Veigas SantoDigital\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)
[error] 
[error] Error: An unexpected error has occurred.
